version: "3"
services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_CONTAINER_NAME}
    ports:
      - ${MYSQL_HOST_PORT}:3306
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw
    restart: always
    networks:
      - local
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}

  redis:
    image: redis:${REDIS_VERSION}
    container_name: ${REDIS_CONTAINER_NAME}
    ports:
      - ${REDIS_HOST_PORT}:6379
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
      - ${REDIS_DATA_DIR}:/data/:rw
    restart: always
    networks:
      - local
    entrypoint: [ "redis-server", "/etc/redis.conf" ]
    environment:
      TZ: ${TZ}

  php:
    build:
      context: ./services/php
      args:
        PHP_VERSION: ${PHP_VERSION}
        ALPINE_VERSION: ${PHP_ALPINE_VERSION}
        COMPOSER_VERSION: ${PHP_COMPOSER_VERSION}
        TZ: ${TZ}
    container_name: ${PHP_CONTAINER_NAME}
    ports:
      - ${PHP_HOST_PORT}:9501
    volumes:
      - ${PHP_CONF_FILE}:/etc/php7/php.ini:ro
      - ${PHP_WWW_DIR}:/data/project/:rw
    restart: always
    depends_on:
      - mysql
      - redis
    networks:
      - local
    entrypoint: [ "tail", "-f", "/dev/null" ]
    environment:
      TZ: ${TZ}

  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}
    container_name: ${RABBITMQ_CONTAINER_NAME}
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_MANAGEMENT_PORT}:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      TZ: "$TZ"
    volumes:
      - ${RABBITMQ_CONF_DIR}:/etc/rabbitmq/conf.d/:rw
      - ${RABBITMQ_DATA_DIR}:/var/lib/rabbitmq/:rw
    restart: always
    networks:
      - local

networks:
  local:
    name: local
    driver: bridge