version: "3"
services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: ${PROJECT_NAME}_mysql
    ports:
      - ${MYSQL_HOST_PORT}:3306
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw
    restart: always
    networks:
      - network0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}

  redis:
    image: redis:${REDIS_VERSION}
    container_name: ${PROJECT_NAME}_redis
    ports:
      - ${REDIS_HOST_PORT}:6379
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
      - ${REDIS_DATA_DIR}:/data/:rw
    restart: always
    networks:
      - network0
    entrypoint: [ "redis-server", "/etc/redis.conf" ]
    environment:
      TZ: ${TZ}

networks:
  network0:
    name: ${PROJECT_NAME}_network
    driver: bridge