version: "3"
services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: ${PROJECT_NAME}_mysql
    ports:
      - ${MYSQL_HOST_PORT}:3306
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw
    restart: always
    networks:
      - network0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}

  redis:
    image: redis:${REDIS_VERSION}
    container_name: ${PROJECT_NAME}_redis
    ports:
      - ${REDIS_HOST_PORT}:6379
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
      - ${REDIS_DATA_DIR}:/data/:rw
    restart: always
    networks:
      - network0
    entrypoint: [ "redis-server", "/etc/redis.conf" ]
    environment:
      TZ: ${TZ}

  php:
    build:
      context: ./services/php
      args:
        PHP_VERSION: ${PHP_VERSION}
        ALPINE_VERSION: ${ALPINE_VERSION}
        COMPOSER_VERSION: ${COMPOSER_VERSION}
        TZ: ${TZ}
    container_name: ${PROJECT_NAME}_php
    ports:
      - ${PHP_HOST_PORT}:9501
    volumes:
      - ${PHP_CONF_FILE}:/etc/php7/php.ini:ro
      - ${WWW_DIR}:/data/project/:rw
    restart: always
    depends_on:
      - mysql
      - redis
    networks:
      - network0
    environment:
      TZ: ${TZ}

networks:
  network0:
    name: ${PROJECT_NAME}_network
    driver: bridge